server:
  port: 9101

spring:
  application:
    name: uster_app
  datasource:
    url: jdbc:h2:file:./data/usterFileDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  mvc:
    format:
      date-time: iso
